parameters:
#    mesd_calendar_calendar.example.class: Mesd\CalendarBundle\Example

services:
#    mesd_calendar_calendar.example:
#        class: %mesd_calendar_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
