calendar_display:
    path:  /show/{calendarService}/{params}/{scope}/{timestamp}
    defaults: { _controller: MesdCalendarBundle:Calendar:displayCalendar, params: 'null', scope: 'Month', timestamp: null}

calendar_display_day:
    path:  /day/{calendarService}/{params}/{timestamp}
    defaults: { _controller: MesdCalendarBundle:Calendar:displayDay, params: ' '}

calendar_display_week:
    path:  /week/{calendarService}/{params}/{timestamp}
    defaults: { _controller: MesdCalendarBundle:Calendar:displayWeek, params: ' '}

calendar_display_month:
    path:  /month/{calendarService}/{params}/{timestamp}
    defaults: { _controller: MesdCalendarBundle:Calendar:displayMonth, params: ' '}
